#!/usr/bin/env bash
# Usage:
#   build.sh <variant> [--patch <file>] [--jobs N] [--cmake-args ...]
#
# 概要:
#   src/mysql-server を cmake + make でビルドして installs/<variant>/ に
#   インストールする。すべての variant で **同じ cmake flags** を使うため、
#   必ずこのスクリプト経由でビルドする (手動で cmake を叩かない)。
#
#   patch を指定すると、ビルド前に git apply で適用し、終了時 (成功・失敗を
#   問わず) に git apply -R で必ず元に戻す。これにより、source tree は常に
#   HEAD のクリーンな状態に保たれる。
#
# 引数・オプション:
#   <variant>            variant 名。builds/<variant>, installs/<variant> が
#                        作られる (例: baseline, nospin-log-mutex)。
#   --patch <file>       patches/<file> を当ててからビルド。ビルド後に
#                        自動で reverse。ファイル名は patches/ からの
#                        相対パスで指定する。
#   --jobs N             make の並列数 (既定は nproc)。
#   --cmake-args ...     追加の cmake 引数。これ以降の引数は全部 cmake に
#                        渡されるので、必ず最後に書く。
#                        通常は不要 — 同じ実験条件に保つために使わない方が
#                        安全。
#
# 使用例:
#   scripts/build.sh baseline
#   scripts/build.sh nospin-log-mutex --patch nospin-log-mutex.patch
#   scripts/build.sh foo --jobs 4
#
# 固定で渡している cmake オプション (全 variant 共通):
#   -DCMAKE_BUILD_TYPE=RelWithDebInfo  最適化を効かせつつ symbol を残す。
#   -DWITH_SSL=system                  ホストの OpenSSL を使う。
#   -DWITH_UNIT_TESTS=OFF              unit test を抜く (ビルド短縮)。
#   -DWITH_TEST_SUITE=OFF              mtr の test suite を抜く。
#   -DDOWNLOAD_BOOST=1                 必要な Boost を自動取得。
#   -DWITH_BOOST=builds/boost_cache    Boost を variant 間で共有。
#
# 注意:
#   - patch 適用前に src ツリーが clean でない場合はエラーで止める。
#     先に make-patch.sh などで整理してから再実行すること。
#   - 同じ variant 名で再実行すると、増分ビルドになる (CMakeCache 再利用)。
#     完全リビルドしたい場合は scripts/clean.sh <variant> を実行してから。

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE="$(cd "$SCRIPT_DIR/.." && pwd)"
SRC="$WORKSPACE/src/mysql-server"

usage() {
  sed -n '/^# Usage:/,/^[^#]/p' "$0" | sed 's/^# \?//'
  exit 1
}

VARIANT=""
PATCH_FILE=""
JOBS="$(nproc)"
CMAKE_EXTRA_ARGS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --patch)      PATCH_FILE="$2"; shift 2 ;;
    --jobs)       JOBS="$2"; shift 2 ;;
    --cmake-args) shift; CMAKE_EXTRA_ARGS+=("$@"); break ;;
    -h|--help)    usage ;;
    -*)           echo "Unknown option: $1"; usage ;;
    *)
      if [[ -z "$VARIANT" ]]; then
        VARIANT="$1"
      else
        echo "Unexpected argument: $1"; usage
      fi
      shift ;;
  esac
done

[[ -z "$VARIANT" ]] && { echo "ERROR: variant name required"; usage; }

BUILD_DIR="$WORKSPACE/builds/$VARIANT"
INSTALL_DIR="$WORKSPACE/installs/$VARIANT"
BOOST_CACHE="$WORKSPACE/builds/boost_cache"

echo "================================================================"
echo " Building variant : $VARIANT"
echo " Source           : $SRC"
echo " Build dir        : $BUILD_DIR"
echo " Install dir      : $INSTALL_DIR"
echo " Jobs             : $JOBS"
[[ -n "$PATCH_FILE" ]] && echo " Patch            : $PATCH_FILE"
echo "================================================================"

# --- Apply patch -----------------------------------------------------------
if [[ -n "$PATCH_FILE" ]]; then
  PATCH_PATH="$WORKSPACE/patches/$PATCH_FILE"
  [[ -f "$PATCH_PATH" ]] || { echo "ERROR: patch not found: $PATCH_PATH"; exit 1; }

  # Check source is clean
  if ! git -C "$SRC" diff --quiet; then
    echo "ERROR: source tree has uncommitted changes. Stash or commit first."
    exit 1
  fi

  echo "--- Applying patch: $PATCH_FILE"
  git -C "$SRC" apply "$PATCH_PATH"

  # Reverse patch on exit (success or failure)
  cleanup() {
    echo "--- Reversing patch: $PATCH_FILE"
    git -C "$SRC" apply -R "$PATCH_PATH" || echo "WARNING: patch reversal failed — check source state"
  }
  trap cleanup EXIT
fi

# --- CMake configure -------------------------------------------------------
mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

cmake "$SRC" \
  -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DWITH_SSL=system \
  -DWITH_UNIT_TESTS=OFF \
  -DWITH_TEST_SUITE=OFF \
  -DDOWNLOAD_BOOST=1 \
  -DWITH_BOOST="$BOOST_CACHE" \
  "${CMAKE_EXTRA_ARGS[@]+"${CMAKE_EXTRA_ARGS[@]}"}"

# --- Build & install -------------------------------------------------------
make -j"$JOBS"
make install

# --- Record BUILD-INFO -----------------------------------------------------
# どの commit / どの patch / どの cmake 引数でビルドしたかを後から
# 追えるようにメタ情報を残す。builds/ と installs/ の両方に書き、
# clean.sh で builds/ を消しても installs/ 側に履歴が残るようにする。
SRC_COMMIT="$(git -C "$SRC" rev-parse HEAD 2>/dev/null || echo unknown)"
{
  echo "# Auto-generated by scripts/build.sh — このファイルは編集しない"
  echo "variant       = $VARIANT"
  echo "date          = $(date -Iseconds)"
  echo "src_commit    = $SRC_COMMIT"
  echo "patch_file    = ${PATCH_FILE:-(none)}"
  echo "build_type    = RelWithDebInfo"
  echo "ssl           = system"
  echo "boost_cache   = $BOOST_CACHE"
  echo "extra_cmake   = ${CMAKE_EXTRA_ARGS[*]:-(none)}"
  echo "jobs          = $JOBS"
  echo "hostname      = $(hostname)"
  echo "user          = $(whoami)"
  echo "cc            = $(cc --version 2>/dev/null | head -1)"
  echo "cxx           = $(c++ --version 2>/dev/null | head -1)"
  echo "cmake         = $(cmake --version 2>/dev/null | head -1)"
} > "$BUILD_DIR/BUILD-INFO.txt"

if [[ -n "$PATCH_FILE" ]]; then
  cp "$WORKSPACE/patches/$PATCH_FILE" "$BUILD_DIR/applied.patch"
fi

# install dir 側にもコピー (build dir は clean.sh で消える可能性あり)
mkdir -p "$INSTALL_DIR"
cp "$BUILD_DIR/BUILD-INFO.txt" "$INSTALL_DIR/BUILD-INFO.txt"
[[ -n "$PATCH_FILE" ]] && cp "$BUILD_DIR/applied.patch" "$INSTALL_DIR/applied.patch"

echo ""
echo "================================================================"
echo " Done: $VARIANT installed to $INSTALL_DIR"
echo " BUILD-INFO: $INSTALL_DIR/BUILD-INFO.txt"
echo " Next step:"
echo "   $SCRIPT_DIR/init-instance.sh $VARIANT"
echo "================================================================"
