#!/usr/bin/env bash
# Usage:
#   init-instance.sh <variant> [--port PORT]
#
# 概要:
#   ビルド済みの variant に対して、そのインスタンス専用の my.cnf と
#   datadir を作って mysqld --initialize-insecure を走らせる。最初の 1 回
#   だけ実行する。
#
#   生成物はすべて installs/<variant>/ 以下に閉じ込めるので、グローバル
#   な /etc/mysql/ や /var/lib/mysql/ は一切触らない (= 隔離されている)。
#
# ディレクトリ構成 (実行後):
#   installs/<variant>/etc/my.cnf   このインスタンス専用の設定ファイル。
#                                    --defaults-file で必ずこれだけを読む。
#   installs/<variant>/data/        InnoDB datadir。
#   installs/<variant>/logs/        error log の出力先。
#   installs/<variant>/run/         mysqld.sock, mysqld.pid。
#   installs/<variant>/tmp/         tmpdir (sort, temp tables)。
#
# 引数・オプション:
#   <variant>      対象 variant (先に build.sh でビルド済みであること)。
#   --port PORT    バインドする TCP ポート (既定: 3307)。
#                  baseline と nospin-log-mutex を並行起動する場合などは
#                  variant ごとに違うポートを指定する (例: baseline=3307,
#                  nospin-log-mutex=3308)。
#
# 使用例:
#   scripts/init-instance.sh baseline               # port 3307 で初期化
#   scripts/init-instance.sh nospin-log-mutex --port 3308
#
# 初期状態の root ユーザはパスワード無しで作られる。必要ならパスワードを
# あとから設定する:
#   scripts/connect.sh <variant> -e \
#     "ALTER USER 'root'@'localhost' IDENTIFIED BY 'yourpassword';"
#
# 注意:
#   - 既に data/ が存在する状態で再実行すると mysqld --initialize-insecure
#     がエラーで止まる (空でないと許さない)。やり直したい場合は
#     先に scripts/clean.sh <variant> --install-only でリセットすること。
#   - my.cnf は毎回このスクリプトのテンプレートから作られる。実験条件を
#     全 variant で揃えたいので、my.cnf を手で編集しないこと。テンプレートを
#     変えたい場合はこのスクリプトの cat <<EOF の中身を編集する。

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE="$(cd "$SCRIPT_DIR/.." && pwd)"

usage() {
  sed -n '/^# Usage:/,/^[^#]/p' "$0" | sed 's/^# \?//'
  exit 1
}

VARIANT=""
PORT=3307
SKIP_INITIALIZE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --port)             PORT="$2"; shift 2 ;;
    --skip-initialize)  SKIP_INITIALIZE=true; shift ;;
    -h|--help) usage ;;
    -*)        echo "Unknown option: $1"; usage ;;
    *)
      if [[ -z "$VARIANT" ]]; then
        VARIANT="$1"
      else
        echo "Unexpected argument: $1"; usage
      fi
      shift ;;
  esac
done

[[ -z "$VARIANT" ]] && { echo "ERROR: variant name required"; usage; }

INSTALL_DIR="$WORKSPACE/installs/$VARIANT"
MYSQLD="$INSTALL_DIR/bin/mysqld"

if [[ ! -x "$MYSQLD" ]]; then
  echo "ERROR: mysqld not found at $MYSQLD"
  echo "       Run: scripts/build.sh $VARIANT"
  exit 1
fi

echo "================================================================"
echo " Initializing instance: $VARIANT"
echo " Install dir : $INSTALL_DIR"
echo " Port        : $PORT"
echo "================================================================"

# --- Create directory layout -----------------------------------------------
mkdir -p "$INSTALL_DIR"/{data,logs,run,tmp,etc}

# --- Write my.cnf -----------------------------------------------------------
# --defaults-file must point to this file; NO global /etc/mysql/ is read.
cat > "$INSTALL_DIR/etc/my.cnf" <<EOF
# Auto-generated by init-instance.sh for variant: $VARIANT
# All paths are relative to this installation — no global MySQL is referenced.

[mysqld]
basedir   = $INSTALL_DIR
datadir   = $INSTALL_DIR/data
socket    = $INSTALL_DIR/run/mysqld.sock
pid-file  = $INSTALL_DIR/run/mysqld.pid
port      = $PORT
log-error = $INSTALL_DIR/logs/mysqld.log
tmpdir    = $INSTALL_DIR/tmp

# Spinlock experiment settings (matches global install baseline)
innodb_adaptive_hash_index        = OFF
innodb_thread_concurrency         = 0

# Disable sync overhead to focus on CPU-side spinlock behavior
sync_binlog                       = 0
innodb_flush_log_at_trx_commit    = 2

# NFS 等 O_DIRECT 非対応ファイルシステム向け（CloudLab など）
innodb_flush_method               = fsync

# Performance Schema — instrument sync objects for spinlock analysis
performance_schema                                    = ON
performance_schema_instrument                         = 'wait/synch/%=ON'
performance_schema_consumer_events_waits_current      = ON
performance_schema_consumer_events_waits_history      = ON
performance_schema_consumer_global_instrumentation    = ON

# Runtime-tunable spinlock parameters (can also be SET GLOBAL at runtime)
# innodb_spin_wait_delay            = 6     # default 6; range 0-1000
# innodb_spin_wait_pause_multiplier = 50    # default 50; range 0-100

max_connections          = 151
innodb_read_io_threads   = 4
innodb_write_io_threads  = 4
innodb_purge_threads     = 1
character-set-server     = utf8mb4

[client]
socket = $INSTALL_DIR/run/mysqld.sock
port   = $PORT
EOF

echo "--- Created: $INSTALL_DIR/etc/my.cnf"

# --- Initialize data directory ---------------------------------------------
if $SKIP_INITIALIZE; then
  echo "--- Skipping mysqld --initialize-insecure (--skip-initialize)"
else
  echo "--- Running mysqld --initialize-insecure (no root password)"
  "$MYSQLD" \
    --defaults-file="$INSTALL_DIR/etc/my.cnf" \
    --initialize-insecure \
    --user="$(whoami)"
fi

echo ""
echo "================================================================"
echo " Instance initialized: $VARIANT"
echo " Start  : $SCRIPT_DIR/start.sh $VARIANT"
echo " Connect: $SCRIPT_DIR/connect.sh $VARIANT"
echo "================================================================"
