#!/usr/bin/env bash
# Usage:
#   setup-emerald.sh [options]
#
# 概要:
#   Emerald Rapids (Intel Xeon Gold 5512U, 28コア×HT=56論理CPU) 専用
#   セットアップスクリプト。
#
#   ルートディスク (/dev/nvme1n1p3) が容量不足になる問題を回避するため、
#   MySQL の可変ファイル（datadir, logs, run, tmp, etc）を /dev/shm 上に置く。
#   installs/<variant>/{data,logs,run,tmp,etc} はシンボリックリンクに置き換えるので、
#   bench-multiplier.sh・connect.sh 等の既存スクリプトはそのまま動作する。
#
#   /dev/shm は RAM ベースの tmpfs（63GB 空き）のためディスク枯渇を回避でき、
#   I/O レイテンシも最小化できる。ただし再起動で消えるため、セッションごとに
#   このスクリプトを再実行すること（prepare も毎回必要）。
#
# コア割り当て:
#   mysqld  : 0-27  (物理コアごとに1スレッド = 28論理CPU)
#   sysbench: 28-31 (4論理CPU)
#
# オプション:
#   --prepare         sysbench prepare を実行（デフォルト: しない）
#   --port     PORT   MySQL ポート番号（デフォルト: 3307）
#   --tables   N      sysbench テーブル数（デフォルト: 8）
#   --table-size N    sysbench テーブル行数（デフォルト: 100000）
#
# 使用例:
#   scripts/setup-emerald.sh --prepare
#
# 注意:
#   再起動後は /dev/shm の内容が消えるため、毎回このスクリプトを実行すること。

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE="$(cd "$SCRIPT_DIR/.." && pwd)"

# --- Emerald 固定値 ---
VARIANT="large-multiplier"
MYSQLD_CORES="0-27"
SYSBENCH_CORES="28-31"
BUFFER_POOL_SIZE="512M"
SHM_BASE="/dev/shm/mysql-lm/$VARIANT"

# --- デフォルト値 ---
PORT=3307
DO_PREPARE=false
TABLES=8
TABLE_SIZE=100000

while [[ $# -gt 0 ]]; do
  case "$1" in
    --port)       PORT="$2";       shift 2 ;;
    --prepare)    DO_PREPARE=true; shift ;;
    --tables)     TABLES="$2";     shift 2 ;;
    --table-size) TABLE_SIZE="$2"; shift 2 ;;
    -h|--help)
      sed -n '/^# Usage:/,/^[^#]/p' "$0" | sed 's/^# \?//'; exit 0 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

INSTALL_DIR="$WORKSPACE/installs/$VARIANT"
MYSQLD="$INSTALL_DIR/bin/mysqld"
MYSQL="$INSTALL_DIR/bin/mysql"
SOCKET="$INSTALL_DIR/run/mysqld.sock"
SYSBENCH="$WORKSPACE/bin/sysbench"

echo "================================================================"
echo " setup-emerald.sh"
echo "  variant          : $VARIANT"
echo "  workspace        : $WORKSPACE"
echo "  port             : $PORT"
echo "  mysqld cores     : $MYSQLD_CORES"
echo "  sysbench cores   : $SYSBENCH_CORES"
echo "  buffer_pool_size : $BUFFER_POOL_SIZE"
echo "  shm base         : $SHM_BASE"
echo "================================================================"

# --- 1. ランタイム依存パッケージ -----------------------------------------------
echo ""
echo "[1/5] Installing runtime dependencies..."
if command -v apt &>/dev/null; then
  sudo apt install -y -q \
    libaio1t64 libssl3t64 libnuma1 libcurl4t64 libtinfo6 git-lfs \
    2>/dev/null || \
  sudo apt install -y -q \
    libaio1 libssl3 libnuma1 libcurl4 libtinfo6 git-lfs \
    2>/dev/null || true
  echo "  apt dependencies done."
else
  echo "  WARNING: apt not found. Skipping."
fi

# Git LFS
if git -C "$WORKSPACE" rev-parse --is-inside-work-tree &>/dev/null; then
  if git lfs version &>/dev/null 2>&1; then
    echo "  Pulling Git LFS objects..."
    git -C "$WORKSPACE" lfs pull 2>/dev/null || true
  fi
fi

[[ -x "$MYSQLD" ]] || {
  echo "ERROR: mysqld not found: $MYSQLD"
  echo "       git lfs pull を実行してください。"
  exit 1
}

# --- 2. sysbench 確認 ---------------------------------------------------------
echo ""
echo "[2/5] Checking sysbench..."
[[ -x "$WORKSPACE/bin/sysbench.bin" ]] || { echo "ERROR: bin/sysbench.bin not found"; exit 1; }
[[ -f "$WORKSPACE/lib/libmysqlclient.so.24" ]] || { echo "ERROR: lib/libmysqlclient.so.24 not found"; exit 1; }
echo "  OK: $($SYSBENCH --version)"

# --- 3. /dev/shm にインスタンスディレクトリを作成し、シンボリックリンクを張る ---
echo ""
echo "[3/5] Preparing /dev/shm instance directories..."

# /dev/shm 上に可変ファイル用ディレクトリを作成
mkdir -p "$SHM_BASE"/{data,logs,run,tmp,etc}

# INSTALL_DIR 以下のディレクトリを /dev/shm へのシンボリックリンクに置き換える
# 既存ディレクトリ（内容あり）は退避せず上書きシンボリックリンクにする
for d in data logs run tmp etc; do
  target="$SHM_BASE/$d"
  link="$INSTALL_DIR/$d"
  if [[ -L "$link" && "$(readlink "$link")" == "$target" ]]; then
    echo "  symlink already correct: $link -> $target"
  else
    # 既存ディレクトリ/シンボリックリンクを削除してシンボリックリンクを作成
    rm -rf "$link"
    ln -s "$target" "$link"
    echo "  symlinked: $link -> $target"
  fi
done

# --- 4. MySQL インスタンス初期化 -----------------------------------------------
echo ""
echo "[4/5] Initializing MySQL instance..."

init_mycnf() {
  cat > "$SHM_BASE/etc/my.cnf" <<EOF
# Auto-generated by setup-emerald.sh — /dev/shm ベース
[mysqld]
basedir   = $INSTALL_DIR
datadir   = $SHM_BASE/data
socket    = $SHM_BASE/run/mysqld.sock
pid-file  = $SHM_BASE/run/mysqld.pid
port      = $PORT
log-error = $SHM_BASE/logs/mysqld.log
tmpdir    = $SHM_BASE/tmp

# /dev/shm (tmpfs) 上のため O_DIRECT 非対応
innodb_flush_method               = fsync

# tmpfs 上は I/O が高速なので buffer pool は最低限
innodb_buffer_pool_size           = $BUFFER_POOL_SIZE

# Spinlock experiment settings
innodb_adaptive_hash_index        = OFF
innodb_thread_concurrency         = 0

# Disable sync overhead
sync_binlog                       = 0
innodb_flush_log_at_trx_commit    = 2

# Performance Schema
performance_schema                                    = ON
performance_schema_instrument                         = 'wait/synch/%=ON'
performance_schema_consumer_events_waits_current      = ON
performance_schema_consumer_events_waits_history      = ON
performance_schema_consumer_global_instrumentation    = ON

max_connections          = 151
innodb_read_io_threads   = 4
innodb_write_io_threads  = 4
innodb_purge_threads     = 1
character-set-server     = utf8mb4

[client]
socket = $SHM_BASE/run/mysqld.sock
port   = $PORT
EOF
  echo "  Created: $SHM_BASE/etc/my.cnf"
}

if [[ -f "$SHM_BASE/data/ibdata1" ]]; then
  echo "  Already initialized (data/ibdata1 exists on /dev/shm). Skipping."
  [[ ! -f "$SHM_BASE/etc/my.cnf" ]] && init_mycnf
else
  echo "  /dev/shm/data is empty — initializing fresh instance."
  init_mycnf
  "$MYSQLD" \
    --defaults-file="$SHM_BASE/etc/my.cnf" \
    --initialize-insecure \
    --user="$(whoami)"
  echo "  Initialized."
fi

# --- 5. MySQL 起動 ------------------------------------------------------------
echo ""
echo "[5/5] Starting MySQL..."
if [[ -S "$SHM_BASE/run/mysqld.sock" ]]; then
  echo "  Already running."
else
  nohup taskset -c "$MYSQLD_CORES" "$MYSQLD" \
    --defaults-file="$SHM_BASE/etc/my.cnf" \
    --user="$(whoami)" \
    >> "$SHM_BASE/logs/mysqld.log" 2>&1 &

  echo -n "  Waiting for socket"
  for i in $(seq 1 30); do
    [[ -S "$SHM_BASE/run/mysqld.sock" ]] && break
    echo -n "."
    sleep 1
  done
  echo ""
  [[ -S "$SHM_BASE/run/mysqld.sock" ]] || {
    echo "ERROR: MySQL did not start."
    echo "       tail -30 $SHM_BASE/logs/mysqld.log"
    exit 1
  }
fi

ACTUAL_M=$("$MYSQL" --socket="$SHM_BASE/run/mysqld.sock" -u root -sN \
  -e "SELECT @@innodb_spin_wait_pause_multiplier;" 2>/dev/null || echo "?")
MAX_M=$("$MYSQL" --socket="$SHM_BASE/run/mysqld.sock" -u root -sN \
  -e "SET GLOBAL innodb_spin_wait_pause_multiplier=10000;
      SELECT @@innodb_spin_wait_pause_multiplier;" 2>/dev/null | tail -1 || echo "?")
"$MYSQL" --socket="$SHM_BASE/run/mysqld.sock" -u root -sN \
  -e "SET GLOBAL innodb_spin_wait_pause_multiplier=50;" 2>/dev/null || true

echo "  Connected. multiplier=$ACTUAL_M (max=$MAX_M)"
[[ "$MAX_M" != "10000" ]] && \
  echo "  WARNING: large-multiplier パッチが効いていません（max=$MAX_M）。"

# --- 6. sysbench prepare ------------------------------------------------------
if $DO_PREPARE; then
  echo ""
  echo "[6/6] Running sysbench prepare..."
  "$MYSQL" --socket="$SHM_BASE/run/mysqld.sock" -u root \
    -e "CREATE DATABASE IF NOT EXISTS sbtest;" 2>/dev/null
  TABLE_COUNT=$("$MYSQL" --socket="$SHM_BASE/run/mysqld.sock" -u root -sN \
    -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='sbtest';" \
    2>/dev/null || echo 0)
  if [[ "$TABLE_COUNT" -ge "$TABLES" ]]; then
    echo "  Tables already exist ($TABLE_COUNT >= $TABLES). Skipping."
  else
    taskset -c "$SYSBENCH_CORES" "$SYSBENCH" oltp_read_write \
      --mysql-socket="$SHM_BASE/run/mysqld.sock" \
      --mysql-user=root \
      --mysql-db=sbtest \
      --tables="$TABLES" \
      --table-size="$TABLE_SIZE" \
      --threads=4 \
      prepare
    echo "  Prepare done (tables=$TABLES, table_size=$TABLE_SIZE)."
  fi
fi

# --- 完了 ---------------------------------------------------------------------
echo ""
echo "================================================================"
echo " Setup complete (emerald): $VARIANT"
echo "  /dev/shm instance : $SHM_BASE"
echo "  ※ 再起動後は /dev/shm の内容が消えるため再実行が必要"
echo ""
echo "  Benchmark:"
echo "    scripts/bench-multiplier.sh $VARIANT \\"
echo "      --server emerald-r650 \\"
echo "      --multipliers 0,5,10,25,50,75,100,150,200,300,500 \\"
echo "      --threads 4,8,16,32,64 \\"
echo "      --mysqld-cores $MYSQLD_CORES \\"
echo "      --sysbench-cores $SYSBENCH_CORES \\"
echo "      --runs 5 --time 60"
echo ""
echo "  Connect:"
echo "    scripts/connect.sh $VARIANT"
echo "================================================================"
