#!/usr/bin/env bash
# Usage:
#   setup-ann.sh [options]
#
# 概要:
#   ann サーバ専用セットアップスクリプト。
#   setup-server.sh の ann 向け特化版。以下の点が異なる:
#
#   1. コア割り当て
#      mysqld  : 0-5  (物理 6 コア)
#      sysbench: 6-7  (2 コア)
#
#   2. innodb_buffer_pool_size = 2G
#      ann は SATA HDD のため、デフォルト 128MB では 8テーブル×100K行（約150MB）が
#      バッファに乗らず HDD シークが多発する。2G に拡大してメモリ上で完結させる。
#
#   3. variant = large-multiplier 固定
#
# オプション:
#   --prepare          sysbench prepare を実行（デフォルト: しない）
#   --port      PORT   MySQL ポート番号（デフォルト: 3307）
#   --tables    N      sysbench テーブル数（デフォルト: 8）
#   --table-size N     sysbench テーブル行数（デフォルト: 100000）
#
# 使用例:
#   scripts/setup-ann.sh --prepare
#   scripts/setup-ann.sh --prepare --tables 8 --table-size 100000

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE="$(cd "$SCRIPT_DIR/.." && pwd)"

# --- ann 固定値 ---
VARIANT="large-multiplier"
MYSQLD_CORES="0-5"
SYSBENCH_CORES="6-7"
BUFFER_POOL_SIZE="2G"

# --- デフォルト値 ---
PORT=3307
DO_PREPARE=false
TABLES=8
TABLE_SIZE=100000

while [[ $# -gt 0 ]]; do
  case "$1" in
    --port)       PORT="$2";       shift 2 ;;
    --prepare)    DO_PREPARE=true; shift ;;
    --tables)     TABLES="$2";     shift 2 ;;
    --table-size) TABLE_SIZE="$2"; shift 2 ;;
    -h|--help)
      sed -n '/^# Usage:/,/^[^#]/p' "$0" | sed 's/^# \?//'; exit 0 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

INSTALL_DIR="$WORKSPACE/installs/$VARIANT"
MYSQLD="$INSTALL_DIR/bin/mysqld"
MYSQL="$INSTALL_DIR/bin/mysql"
SOCKET="$INSTALL_DIR/run/mysqld.sock"
SYSBENCH="$WORKSPACE/bin/sysbench"

echo "================================================================"
echo " setup-ann.sh"
echo "  variant          : $VARIANT"
echo "  workspace        : $WORKSPACE"
echo "  port             : $PORT"
echo "  mysqld cores     : $MYSQLD_CORES"
echo "  sysbench cores   : $SYSBENCH_CORES"
echo "  buffer_pool_size : $BUFFER_POOL_SIZE"
echo "================================================================"

# --- 1. ランタイム依存パッケージ -----------------------------------------------
echo ""
echo "[1/5] Installing runtime dependencies..."
if command -v apt &>/dev/null; then
  sudo apt install -y -q \
    libaio1t64 libssl3t64 libnuma1 libcurl4t64 libtinfo6 git-lfs \
    2>/dev/null || \
  sudo apt install -y -q \
    libaio1 libssl3 libnuma1 libcurl4 libtinfo6 git-lfs \
    2>/dev/null || true
  echo "  apt dependencies done."
else
  echo "  WARNING: apt not found. Skipping."
fi

# --- 2. Git LFS ---
if git -C "$WORKSPACE" rev-parse --is-inside-work-tree &>/dev/null; then
  if git lfs version &>/dev/null 2>&1; then
    echo "  Pulling Git LFS objects..."
    git -C "$WORKSPACE" lfs pull 2>/dev/null || true
  fi
fi

[[ -x "$MYSQLD" ]] || {
  echo "ERROR: mysqld not found: $MYSQLD"
  echo "       git lfs pull を実行してください。"
  exit 1
}

# --- 2. sysbench 確認 ---------------------------------------------------------
echo ""
echo "[2/5] Checking sysbench..."
[[ -x "$WORKSPACE/bin/sysbench.bin" ]] || { echo "ERROR: bin/sysbench.bin not found"; exit 1; }
[[ -f "$WORKSPACE/lib/libmysqlclient.so.24" ]] || { echo "ERROR: lib/libmysqlclient.so.24 not found"; exit 1; }
echo "  OK: $($SYSBENCH --version)"

# --- 3. MySQL インスタンス初期化 -----------------------------------------------
echo ""
echo "[3/5] Initializing MySQL instance..."

init_mycnf() {
  mkdir -p "$INSTALL_DIR"/{data,logs,run,tmp,etc}
  cat > "$INSTALL_DIR/etc/my.cnf" <<EOF
# Auto-generated by setup-ann.sh for variant: $VARIANT
[mysqld]
basedir   = $INSTALL_DIR
datadir   = $INSTALL_DIR/data
socket    = $INSTALL_DIR/run/mysqld.sock
pid-file  = $INSTALL_DIR/run/mysqld.pid
port      = $PORT
log-error = $INSTALL_DIR/logs/mysqld.log
tmpdir    = $INSTALL_DIR/tmp

# ann 専用: HDD でも全データがバッファに乗るよう大きめに設定
innodb_buffer_pool_size           = $BUFFER_POOL_SIZE

# Spinlock experiment settings
innodb_adaptive_hash_index        = OFF
innodb_thread_concurrency         = 0

# Disable sync overhead
sync_binlog                       = 0
innodb_flush_log_at_trx_commit    = 2

# NFS 等 O_DIRECT 非対応ファイルシステム向け
innodb_flush_method               = fsync

# Performance Schema
performance_schema                                    = ON
performance_schema_instrument                         = 'wait/synch/%=ON'
performance_schema_consumer_events_waits_current      = ON
performance_schema_consumer_events_waits_history      = ON
performance_schema_consumer_global_instrumentation    = ON

max_connections          = 151
innodb_read_io_threads   = 4
innodb_write_io_threads  = 4
innodb_purge_threads     = 1
character-set-server     = utf8mb4

[client]
socket = $INSTALL_DIR/run/mysqld.sock
port   = $PORT
EOF
  echo "  Created: $INSTALL_DIR/etc/my.cnf"
}

if [[ -f "$INSTALL_DIR/data/ibdata1" ]]; then
  echo "  Already initialized (data/ibdata1 exists). Skipping --initialize-insecure."
  if [[ ! -f "$INSTALL_DIR/etc/my.cnf" ]]; then
    echo "  my.cnf missing. Regenerating..."
    init_mycnf
  fi
else
  init_mycnf
  echo "  Running mysqld --initialize-insecure..."
  "$MYSQLD" \
    --defaults-file="$INSTALL_DIR/etc/my.cnf" \
    --initialize-insecure \
    --user="$(whoami)"
  echo "  Initialized."
fi

# --- 4. MySQL 起動 ------------------------------------------------------------
echo ""
echo "[4/5] Starting MySQL..."
if [[ -S "$SOCKET" ]]; then
  echo "  Already running."
else
  nohup taskset -c "$MYSQLD_CORES" "$MYSQLD" \
    --defaults-file="$INSTALL_DIR/etc/my.cnf" \
    --user="$(whoami)" \
    >> "$INSTALL_DIR/logs/mysqld.log" 2>&1 &

  echo -n "  Waiting for socket"
  for i in $(seq 1 30); do
    [[ -S "$SOCKET" ]] && break
    echo -n "."
    sleep 1
  done
  echo ""
  [[ -S "$SOCKET" ]] || {
    echo "ERROR: MySQL did not start."
    echo "       tail -30 $INSTALL_DIR/logs/mysqld.log"
    exit 1
  }
fi

ACTUAL_M=$("$MYSQL" --socket="$SOCKET" -u root -sN \
  -e "SELECT @@innodb_spin_wait_pause_multiplier;" 2>/dev/null || echo "?")
MAX_M=$("$MYSQL" --socket="$SOCKET" -u root -sN \
  -e "SET GLOBAL innodb_spin_wait_pause_multiplier=10000;
      SELECT @@innodb_spin_wait_pause_multiplier;" 2>/dev/null | tail -1 || echo "?")
"$MYSQL" --socket="$SOCKET" -u root -sN \
  -e "SET GLOBAL innodb_spin_wait_pause_multiplier=50;" 2>/dev/null || true

BP=$("$MYSQL" --socket="$SOCKET" -u root -sN \
  -e "SELECT ROUND(@@innodb_buffer_pool_size/1024/1024/1024,1);" 2>/dev/null || echo "?")

echo "  Connected. multiplier=$ACTUAL_M (max=$MAX_M), buffer_pool=${BP}G"
[[ "$MAX_M" != "10000" ]] && \
  echo "  WARNING: large-multiplier パッチが効いていません（max=$MAX_M）。"

# --- 5. sysbench prepare ------------------------------------------------------
if $DO_PREPARE; then
  echo ""
  echo "[5/5] Running sysbench prepare..."
  "$MYSQL" --socket="$SOCKET" -u root -e "CREATE DATABASE IF NOT EXISTS sbtest;" 2>/dev/null
  TABLE_COUNT=$("$MYSQL" --socket="$SOCKET" -u root -sN \
    -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='sbtest';" 2>/dev/null || echo 0)
  if [[ "$TABLE_COUNT" -ge "$TABLES" ]]; then
    echo "  Tables already exist ($TABLE_COUNT >= $TABLES). Skipping."
  else
    taskset -c "$SYSBENCH_CORES" "$SYSBENCH" oltp_read_write \
      --mysql-socket="$SOCKET" \
      --mysql-user=root \
      --mysql-db=sbtest \
      --tables="$TABLES" \
      --table-size="$TABLE_SIZE" \
      --threads=4 \
      prepare
    echo "  Prepare done (tables=$TABLES, table_size=$TABLE_SIZE)."
  fi
else
  echo ""
  echo "[5/5] Skipping sysbench prepare (--prepare not specified)."
fi

# --- 完了 ---------------------------------------------------------------------
echo ""
echo "================================================================"
echo " Setup complete (ann): $VARIANT"
echo ""
echo "  Benchmark:"
echo "    scripts/bench-multiplier.sh $VARIANT \\"
echo "      --server skylake-ann \\"
echo "      --multipliers 0,5,10,25,50,75,100,150,200,300,500 \\"
echo "      --threads 4,8,16,32,64 \\"
echo "      --mysqld-cores $MYSQLD_CORES \\"
echo "      --sysbench-cores $SYSBENCH_CORES \\"
echo "      --runs 5 --time 60"
echo ""
echo "  Connect:"
echo "    scripts/connect.sh $VARIANT"
echo "================================================================"
